### ISSUE TITLE
iOS build errors

### ISSUE THREAD

**Issue by michela** [feixuwu/UEWebsocket#7]
On 4.18.1 I haven't been able to do an iOS remote build. 

The UnrealBuildTool function PublicLibraryPaths.Add seems to always escape the final " and put a newline... can't work it out

```
-L"ThirdParty/FreeType2/FreeType2-2.4.12/Lib/ios/Device" -L"ThirdParty/libPNG/libPNG-1.5.2/lib/ios/Device" -L"ThirdParty/PhysX/Lib/IOS/" -L"D:\Perforce\michela_ZOD_3960\ue4\INFS1020\Collaboration\INFS1020\INFS1020\Plugins\WebSocket\Source\WebSocket\ThirdParty\lib\IOS
\" -L"ThirdParty/PhysX/Lib/IOS" -l"z" "/Users/michela/UE4/Builds/ZOD/D/Program Files/Epic Games/UE_4.18/Engine/Source/ThirdParty/PLCrashReporter/plcrashreporter-master-5ae3b0a/IOS/Release/libCrashReporter-iphoneos.a" "/Users/michela/UE4/Builds/ZOD/D/Program Files/Epic Games/UE_4.18/Engine/Source/ThirdParty/ICU/icu4c-53_1/IOS/lib/libicudata.a" 
L"D:\Perforce\michela_ZOD_3960\ue4\INFS1020\Collaboration\INFS1020\INFS1020\Plugins\WebSocket\Source\WebSocket\ThirdParty\lib\IOS
\"
```

Plugin works perfectly well on Windows but in Plugins if you click Package you also get errors. 

Installed this in the project root. Plugin didn't work when putting in Engine/Plugins

**Comment by michela** [comment]
Here's full output log from package to ios. I can't work out how to fix the path issue. Tried hacking the plugin build script with no luck.
[dump.txt](https://github.com/feixuwu/UEWebsocket/files/1545257/dump.txt)

**Comment by feixuwu** [comment]
I have not tested ios remote build, I will take time to fix it next sevral days

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
Hi, I fixed this bug, please clone the new version and should be fine.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by michela** [comment]
Works! That's great. Thanks for such quick response.

**Comment by feixuwu** [comment]
still have problem?

**Comment by michela** [comment]
Spoke too soon. On a larger project that uses UEWebsocket, I no longer get build errors iOS with no errors but no websocket connection success either. 

On the UEWebsocket sample project (same host and remote build server settings), I still can't remote build  with link errors

[UATHelper: Packaging (iOS):   ld: warning: directory not found for option '-LC:/Users/michela/src/UEWebsocket/Plugins/WebSocket/Source/WebSocket/ThirdParty/lib/IOS/'
UATHelper: Packaging (iOS):   
UATHelper: Packaging (iOS):   ld: library not found for -lwebsockets
UATHelper: Packaging (iOS):   
UATHelper: Packaging (iOS):   clang: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (iOS):   Doing bash -c 'if [ -e "/Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/Plugins/WebSocket/Binaries/IOS/UE4-WebSocket.a" ]; then eval $(stat -s "/Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/Plugins/WebSocket/Binaries/IOS/UE4-WebSocket.a") && echo $st_mtime,$st_size; fi'
UATHelper: Packaging (iOS):   Execute took 00:00:00.4827947
UATHelper: Packaging (iOS):   Doing bash -c 'if [ -e "/Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/Binaries/IOS/UEWebsocket" ]; then eval $(stat -s "/Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/Binaries/IOS/UEWebsocket") && echo $st_mtime,$st_size; fi'
UATHelper: Packaging (iOS):   Execute took 00:00:00.4879119
UATHelper: Packaging (iOS):   ERROR: UBT ERROR: Failed to produce item: /Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/Binaries/IOS/UEWebsocket
UATHelper: Packaging (iOS):   Total build time: 57.91 seconds (Remote executor: 0.00 seconds)
UATHelper: Packaging (iOS): Took 58.196623s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (iOS): ERROR: Command failed (Result:5): D:\Program Files\Epic Games\UE_4.18\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket IOS Development -Project=C:\Users\michela\src\UEWebsocket\UEWebsocket.uproject  C:\Users\michela\src\UEWebsocket\UEWebsocket.uproject -NoUBTMakefiles  -remoteini="C:\Users\michela\src\UEWebsocket" -skipdeplo
y -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2017.12.11-11.14.45.txt' 
UATHelper: Packaging (iOS):        (see C:\Users\michela\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_4.18\UAT_Log.txt for full exception trace)
UATHelper: Packaging (iOS): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (iOS): BUILD FAILED
PackagingResults: Error: Unknown Error](url)

**Comment by michela** [comment]
I've deleted Build, Intermedia and Saved folders before repackaging to check not using old settings. Are there any additional steps you recommend to ensure not using incorrect cached data? Don't understand why sample isn't working but other project is.

**Comment by feixuwu** [comment]
hi, did you delete the project on your mac? login to your mac and then delete the directory /Users/michela/UE4/Builds/ZOD/C/Users/michela/src/UEWebsocket/
and try agian? I guess the unreal engine 4 remote build will not update the build.cs on the mac.

**Comment by michela** [comment]
Getting same error after deleting entire project from mac

But some good news, websockets working on iOS in my real project now. Thank for support. Made a deployment error. 

Puzzled about the sample project though. I deleted and recloned and still getting that error

**Comment by feixuwu** [comment]
I don't have a mac current, I'll do the test after my day work.
I used the plugin on my own .io game.

**Comment by feixuwu** [comment]
test again on my mac, works fine.
